// DMP SIM LAB – historische Sport- und Kampflegenden.
// Biografische Angaben: Links bei jedem Profil. Sämtliche Zahlen (Masse,
// Bewegungs- und Kampfwerte) sind illustrative Spiel-/Trainingsprofile,
// keine historischen Leistungs- oder medizinischen Daten.
const G={aggression:.59,guard:.40,jump:.30,punch:.56,kick:.41,push:.39,range:.46,
 stride:.46,cadence:.55,footwork:.52,evade:.38,spring:.48,balance:.56,recovery:.52};
function style(p){return Object.freeze({...G,...p});}
export const FIGHTER_CATALOG=Object.freeze([
 {key:"ali",name:"Muhammad Ali",emoji:"🥊",type:"Boxen",appearance:"human",fighterStyle:"ali",kind:"biped",
  color:"#df404a",mass:96,amplitude:.81,frequency:2.25,feedback:6.2,traction:.91,endurance:.89,torso:1.02,limb:1.25,head:.96,
  combat:style({aggression:.58,guard:.72,jump:.18,punch:.95,kick:.09,push:.20,range:.88,stride:.82,cadence:.85,footwork:.96,evade:.92,spring:.43,balance:.78,recovery:.86}),
  talent:"Distanzarbeit · flinke Fußarbeit · Konterboxen",
  fact:"Olympiasieger 1960 und mehrfacher Schwergewichtsweltmeister. Berühmt für Beweglichkeit und Ringintelligenz. Gewicht und Kampfwerte sind fiktive Modellwerte.",
  source:"https://www.archives.gov/research/african-americans/individuals/muhammad-ali"},
 {key:"tyson",name:"Mike Tyson",emoji:"🥊",type:"Boxen",appearance:"human",fighterStyle:"tyson",kind:"biped",
  color:"#252b34",mass:100,amplitude:.75,frequency:2.3,feedback:5.9,traction:.93,endurance:.76,torso:1.35,limb:.94,head:.97,
  combat:style({aggression:.96,guard:.84,jump:.12,punch:.99,kick:.08,push:.55,range:.20,stride:.65,cadence:.89,footwork:.85,evade:.67,spring:.33,balance:.83,recovery:.80}),
  talent:"Explosive Nahdistanz · Deckung · Schlagkombinationen",
  fact:"1986 jüngster Schwergewichts-Weltmeister. Bekannt für Peek-a-boo-Deckung und schnelle Schlagserien. Gewicht und Kampfwerte sind Modellannahmen.",
  source:"https://boxhall.wixsite.com/ibhof/mike-tyson"},
 {key:"shields",name:"Claressa Shields",emoji:"🥇",type:"Boxen",appearance:"human",fighterStyle:"shields",kind:"biped",
  color:"#815ec6",mass:75,amplitude:.72,frequency:2.15,feedback:6.4,traction:.92,endurance:.92,torso:.94,limb:1.08,head:.97,
  combat:style({aggression:.70,guard:.89,jump:.16,punch:.92,kick:.07,push:.22,range:.70,stride:.70,cadence:.89,footwork:.87,evade:.80,spring:.36,balance:.87,recovery:.91}),
  talent:"Präzise Kombinationen · Deckung · Ringkontrolle",
  fact:"Olympisches Boxgold 2012 und 2016 für die USA. Auch professionelle Weltmeisterin in mehreren Gewichtsklassen. Alle Spielwerte sind frei modelliert.",
  source:"https://www.teamusa.com/profiles/claressa-shields-817852"},
 {key:"bruce",name:"Bruce Lee",emoji:"🐉",type:"Jeet Kune Do",appearance:"human",fighterStyle:"bruce",kind:"biped",
  color:"#e9bc3d",mass:64,amplitude:.86,frequency:2.6,feedback:6.5,traction:.92,endurance:.86,torso:.91,limb:1.07,head:.89,
  combat:style({aggression:.75,guard:.62,jump:.75,punch:.90,kick:.94,push:.44,range:.67,stride:.83,cadence:.98,footwork:.97,evade:.91,spring:.87,balance:.88,recovery:.88}),
  talent:"Variable Distanzen · schnelle Fußarbeit · Abfangen",
  fact:"Kampfkünstler und Filmikone, entwickelte Jeet Kune Do. Im Modell sind Geschwindigkeit und Kampfstil bewusst idealisiert.",
  source:"https://brucelee.com/jeet-kune-do"},
 {key:"oyama",name:"Mas Oyama",emoji:"🥋",type:"Karate",appearance:"human",fighterStyle:"oyama",kind:"biped",
  color:"#f2f1e9",mass:82,amplitude:.65,frequency:1.75,feedback:6.0,traction:.94,endurance:.97,torso:1.10,limb:1.05,head:.98,
  combat:style({aggression:.79,guard:.74,jump:.18,punch:.91,kick:.89,push:.69,range:.52,stride:.55,cadence:.71,footwork:.70,evade:.51,spring:.49,balance:.94,recovery:.93}),
  talent:"Kyokushin-Karate · Standfestigkeit · Kondition",
  fact:"Begründer des Kyokushin-Karate. Spielwerte spiegeln eine interpretierte Karate-Rolle, keine historischen Messungen.",
  source:"https://www.mas-oyama.com/history"},
 {key:"ronda",name:"Ronda Rousey",emoji:"🥋",type:"Judo / MMA",appearance:"human",fighterStyle:"ronda",kind:"biped",
  color:"#467bc2",mass:68,amplitude:.66,frequency:1.95,feedback:6.7,traction:.96,endurance:.89,torso:1.0,limb:1.04,head:.92,
  combat:style({aggression:.88,guard:.60,jump:.14,punch:.49,kick:.37,push:.97,range:.23,stride:.61,cadence:.74,footwork:.69,evade:.55,spring:.40,balance:.98,recovery:.81}),
  talent:"Judo-Wurftechnik · Griffkampf · Gleichgewicht",
  fact:"Olympiabronze 2008 im Judo; anschließend UFC-Meisterin im MMA. Das aktuelle Duell modelliert keine Würfe oder Aufgabegriffe – hohe Schub-/Balancewerte sind nur eine Annäherung.",
  source:"https://www.ijf.org/judoka/2589"},
 {key:"riner",name:"Teddy Riner",emoji:"🥇",type:"Judo",appearance:"human",fighterStyle:"riner",kind:"biped",
  color:"#f8f7ee",mass:138,amplitude:.60,frequency:1.70,feedback:7.3,traction:.97,endurance:.88,torso:1.48,limb:1.24,head:.92,
  combat:style({aggression:.65,guard:.90,jump:.12,punch:.25,kick:.17,push:.99,range:.44,stride:.57,cadence:.64,footwork:.66,evade:.59,spring:.37,balance:.99,recovery:.93}),
  talent:"Judo · starker Stand · Schwerpunktkontrolle",
  fact:"Judo-Olympiasieger in London 2012, Rio 2016 und Paris 2024 (+100 kg). Im bestehenden Duell gibt es keine echten Judo-Würfe.",
  source:"https://www.ijf.org/news/show/teddy-riner-s-historic-win-at-the-paris-2024-olympic-games"},
 {key:"saenchai",name:"Saenchai",emoji:"🦵",type:"Muay Thai",appearance:"human",fighterStyle:"saenchai",kind:"biped",
  color:"#dd4f67",mass:65,amplitude:.84,frequency:2.45,feedback:6.3,traction:.92,endurance:.92,torso:.88,limb:1.17,head:.92,
  combat:style({aggression:.76,guard:.78,jump:.61,punch:.75,kick:.99,push:.50,range:.73,stride:.80,cadence:.92,footwork:.93,evade:.93,spring:.85,balance:.93,recovery:.87}),
  talent:"Muay-Thai-Kicks · Ausweichen · kreative Winkel",
  fact:"Thailändischer Muay-Thai-Champion, bekannt für außergewöhnliche Technik, Ausweichen und kreative Beinarbeit. Zahlen sind Spielwerte.",
  source:"https://www.muaythaipedia.com/saenchai/"},
 {key:"khabib",name:"Khabib Nurmagomedov",emoji:"🦅",type:"MMA / Sambo",appearance:"human",fighterStyle:"khabib",kind:"biped",
  color:"#38777a",mass:70,amplitude:.70,frequency:1.95,feedback:6.8,traction:.97,endurance:.99,torso:1.11,limb:1.05,head:.95,
  combat:style({aggression:.95,guard:.85,jump:.11,punch:.53,kick:.33,push:.99,range:.19,stride:.66,cadence:.77,footwork:.83,evade:.65,spring:.35,balance:.98,recovery:.96}),
  talent:"Sambo · Druck · Ringen / Kontrolle",
  fact:"Ehemaliger UFC-Leichtgewichtschampion, ungeschlagene MMA-Karriere (29–0). Das Simulationsmodell kann Bodenkampf nicht realistisch darstellen.",
  source:"https://www.ufc.com/athlete/khabib-nurmagomedov"},
 {key:"musashi",name:"Miyamoto Musashi",emoji:"⚔️",type:"Historischer Samurai",appearance:"human",fighterStyle:"musashi",kind:"biped",
  color:"#5e798c",mass:75,amplitude:.69,frequency:1.80,feedback:6.5,traction:.88,endurance:.90,torso:1.05,limb:1.04,head:.93,
  combat:style({aggression:.60,guard:.97,jump:.19,punch:.51,kick:.31,push:.48,range:.96,stride:.68,cadence:.74,footwork:.77,evade:.83,spring:.40,balance:.92,recovery:.94}),
  talent:"Historische Schwertkunst · Timing · Distanz",
  fact:"Japanischer Schwertkünstler; die Niten-Ichi-ryū-Schule ist mit der Arbeit mit zwei Schwertern verbunden. Die Schwertkunst ist hier nur grafisch und strategisch inspiriert; die Duell-Arena simuliert keine Waffen.",
  source:"https://www.niten.org/english/instituto/miyamoto_musashi/musashi-biografia"}
].map(x=>Object.freeze(x)));
